# fly.toml app configuration file generated for ga02-auth on 2023-11-28T12:37:15+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ga02-auth"
primary_region = "sin"
kill_timeout = 300

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
